apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: rasa
spec:
  secretName: rasa-x-tsl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: AlzheimerChatbot.com
  dnsNames:
  - http://192.168.1.52