version: '3'
services:
  rasa:
    container_name: sdc-rasa-chatbot
    image: rasa/rasa:latest
    ports:
      #- 5006:5006
      - 5005:5005
    volumes:
      - .:/app
    command:
      - run
      #- --ssl-certificate
      #- ssl.pem
      #- --ssl-keyfile
      #- ssl.key
      - -m
      - models
      - --cors
      - "*"
    depends_on:
      - action-server
  action-server:
    container_name: sdc-action
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055